import type { Metadata } from 'next';
import React from 'react';
import { Montserrat } from 'next/font/google';
import '../styles/globals.css';
import Container from '@/components/layout/Container/Container';
import StyledComponentsRegistry from '../../lib/registry';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={montserrat.variable}>
      <body className={montserrat.className}>
        <StyledComponentsRegistry>
          <Container>{children}</Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
