import type { Metadata } from 'next';
import React from 'react';
import { Montserrat } from 'next/font/google';
import '../styles/globals.css';
import AuthChecker from '@/components/auth/AuthChecker/AuthChecker';
import { getCurrentUser } from '@/lib/utils/auth';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  const isAuthenticated = !!user?.id;

  return (
    <html lang="fr" className={montserrat.variable}>
      <body className={montserrat.className}>
        <AuthChecker isAuthenticated={isAuthenticated}>{children}</AuthChecker>
      </body>
    </html>
  );
}
